# Generated by Django 5.1.3 on 2024-11-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rse_challenges_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_url',
            new_name='url',
        ),
    ]
